name: docs_env_sectionate
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - cartopy
  - cftime
  - ipython
  - jupyterlab
  - matplotlib
  - netcdf4
  - pydap
  - pytest
  - sphinx
  - nbsphinx
  - myst-parser
  - pandoc
  - ffmpeg
  - ipykernel
  - pip
