name: binder_env_sectionate
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cartopy
  - cftime
  - dask
  - ipython
  - jupyterlab
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - pip
  - pydap
  - pytest
  - pip:
    - cmip_basins
    - git+https://github.com/raphaeldussin/xoverturning.git@4aa055be39580e5eef6b4e22cc8693410ee3cf77
